# IO configuration for 2x2
# Revision date: August 19, 2024

__meta__:
  version: "240819"
  date: "2024-08-19"
  description: "IO configuration for 2x2 August 2024"
  compatible_with:
    base: ">=240719"
  tags: [no-ppn-point-tagging]

include: io_common.yaml

override:
  # Exclude point tagging in PPN label parser
  io.loader.dataset.schema.ppn_label.include_point_tagging: false
