# 2x2 model configuration
# Revision date: August 19, 2024

__meta__:
  version: "240819"
  date: "2024-08-19"
  description: "2x2 model with average charge rescaling"
  compatible_with:
    base: ">=240719"
    io: ">=240819"
  tags: []
  training_set: "v2"

include: model_common.yaml

override:
  # Path to the v2 model weights
  model.weight_path: !download
    url: https://s3df.slac.stanford.edu/data/neutrino/spine/weights/2x2/2x2_snapshot_240819.ckpt
    hash: a0d5609e24abe8e88884d39ea6c0fcf4b507141bbc637fdf200cb404dfbd1bb0

  # Direction and dE/dx radii settings for GrapPA modules
  model.modules.grappa_shower.node_encoder.dir_max_dist: -1
  model.modules.grappa_shower.node_encoder.dedx_max_dist: -1
  model.modules.grappa_track.node_encoder.dir_max_dist: -1
  model.modules.grappa_track.node_encoder.dedx_max_dist: -1
  model.modules.grappa_inter.node_encoder.dir_max_dist: -1
  model.modules.grappa_inter.node_encoder.dedx_max_dist: -1
